"""
Common utilities and type definitions.

This module provides shared functionality across the entire system.
"""

from .calendar import (
    TradingCalendar,
    get_calendar,
    get_next_trading_day,
    get_previous_trading_day,
    get_trading_days,
    is_trading_day,
    set_calendar,
)
from .logging import (
    LogContext,
    get_logger,
    log_config,
    log_dataframe_info,
    log_metrics,
    setup_logging,
)
from .types import (
    AllocationMethod,
    BacktestConfig,
    FeatureRow,
    LabelRow,
    Order,
    OrderStatus,
    OrderType,
    PortfolioConfig,
    PortfolioWeight,
    RebalanceFrequency,
    RegimeProbability,
    RegimeType,
    RiskConfig,
    SignalScore,
    Trade,
    features_df_from_rows,
    signals_df_from_scores,
    validate_features_df,
    validate_labels_df,
    validate_prices_df,
    validate_signals_df,
    validate_weights_df,
    weights_df_from_weights,
)
from .utils import (
    ensure_datetime_index,
    ensure_dir,
    filter_date_range,
    get_artifacts_dir,
    get_config_dir,
    get_data_dir,
    get_project_root,
    get_reports_dir,
    hash_dataframe,
    hash_dict,
    load_json,
    load_parquet,
    load_pickle,
    load_yaml,
    melt_to_long,
    pivot_to_wide,
    rank_percentile,
    safe_divide,
    save_json,
    save_parquet,
    save_pickle,
    save_yaml,
    set_seed,
    winsorize,
    zscore,
)

__all__ = [
    # Types
    "AllocationMethod",
    "BacktestConfig",
    "FeatureRow",
    "LabelRow",
    "Order",
    "OrderStatus",
    "OrderType",
    "PortfolioConfig",
    "PortfolioWeight",
    "RebalanceFrequency",
    "RegimeProbability",
    "RegimeType",
    "RiskConfig",
    "SignalScore",
    "Trade",
    # Type utilities
    "features_df_from_rows",
    "signals_df_from_scores",
    "weights_df_from_weights",
    "validate_features_df",
    "validate_labels_df",
    "validate_prices_df",
    "validate_signals_df",
    "validate_weights_df",
    # Calendar
    "TradingCalendar",
    "get_calendar",
    "set_calendar",
    "is_trading_day",
    "get_trading_days",
    "get_previous_trading_day",
    "get_next_trading_day",
    # Logging
    "setup_logging",
    "get_logger",
    "log_config",
    "log_metrics",
    "log_dataframe_info",
    "LogContext",
    # Utils
    "set_seed",
    "load_yaml",
    "save_yaml",
    "load_json",
    "save_json",
    "load_parquet",
    "save_parquet",
    "load_pickle",
    "save_pickle",
    "ensure_datetime_index",
    "filter_date_range",
    "pivot_to_wide",
    "melt_to_long",
    "winsorize",
    "zscore",
    "rank_percentile",
    "safe_divide",
    "hash_dict",
    "hash_dataframe",
    "ensure_dir",
    "get_project_root",
    "get_data_dir",
    "get_config_dir",
    "get_artifacts_dir",
    "get_reports_dir",
]
